# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import csv

# The class for the Ui_EditWindow, the 2nd window
class Ui_EditWindow(object):
#Function for the setupUI , setting of the UI buttons,Input widgets , and etc
    def setupUi(self, EditWindow):
        EditWindow.setObjectName("EditWindow")
        EditWindow.resize(640, 480)
        EditWindow.setStyleSheet("background-color: rgb(255, 240, 210);\n"
"border-color: rgb(39, 24, 255);")


        self.centralwidget = QtWidgets.QWidget(EditWindow)
        self.centralwidget.setObjectName("centralwidget")




        self.labelID_Number2W = QtWidgets.QLabel(self.centralwidget)
        self.labelID_Number2W.setGeometry(QtCore.QRect(10, 70, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelID_Number2W.setFont(font)
        self.labelID_Number2W.setObjectName("labelID_Number2W")

        
        self.labelID_Number3W = QtWidgets.QLabel(self.centralwidget)
        self.labelID_Number3W.setGeometry(QtCore.QRect(10, 30, 190, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(75)
        self.labelID_Number3W.setFont(font)
        self.labelID_Number3W.setObjectName("labelID_Number3W")

        self.labelName2W = QtWidgets.QLabel(self.centralwidget)
        self.labelName2W.setGeometry(QtCore.QRect(10, 110, 75, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelName2W.setFont(font)
        self.labelName2W.setObjectName("labelName2W")
        self.labelCourse2w = QtWidgets.QLabel(self.centralwidget)
        self.labelCourse2w.setGeometry(QtCore.QRect(10, 150, 75, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelCourse2w.setFont(font)
        self.labelCourse2w.setObjectName("labelCourse2w")
        self.labelYearlevel2W = QtWidgets.QLabel(self.centralwidget)
        self.labelYearlevel2W.setGeometry(QtCore.QRect(10, 190, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelYearlevel2W.setFont(font)
        self.labelYearlevel2W.setObjectName("labelYearlevel2W")
        self.labelGender2W = QtWidgets.QLabel(self.centralwidget)
        self.labelGender2W.setGeometry(QtCore.QRect(10, 230, 75, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelGender2W.setFont(font)
        self.labelGender2W.setObjectName("labelGender2W")
        self.pushButtonUpdate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonUpdate.setGeometry(QtCore.QRect(130, 300, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonUpdate.setFont(font)
        self.pushButtonUpdate.setStyleSheet("background-color: rgb(227, 255, 226);\n"
"border-color: rgb(73, 76, 255);")
        self.pushButtonUpdate.setObjectName("pushButtonUpdate")
        self.pushButtonUpdate.clicked.connect(self.edit_student)




        
        self.lineEditIDNumber2W = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditIDNumber2W.setGeometry(QtCore.QRect(120, 70, 200, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEditIDNumber2W.setFont(font)
        self.lineEditIDNumber2W.setStyleSheet("background-color: rgb(229, 255, 252);")
        self.lineEditIDNumber2W.setObjectName("lineEditIDNumber2W")

        self.lineEditIDNumber3W = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditIDNumber3W.setGeometry(QtCore.QRect(180, 30, 200, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEditIDNumber3W.setFont(font)
        self.lineEditIDNumber3W.setStyleSheet("background-color: rgb(229, 255, 252);")
        self.lineEditIDNumber3W.setObjectName("lineEditIDNumber3W")

        self.lineEditName2W = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditName2W.setGeometry(QtCore.QRect(120, 110, 200, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEditName2W.setFont(font)
        self.lineEditName2W.setStyleSheet("background-color: rgb(229, 255, 252);")
        self.lineEditName2W.setObjectName("lineEditName2W")


        self.comboBoxYearLevel = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxYearLevel.setGeometry(QtCore.QRect(120, 190, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboBoxYearLevel.setFont(font)
        self.comboBoxYearLevel.setStyleSheet("background-color: rgb(229, 255, 252);\n"
        "border :2px solid ;\n"
        "border-radius:2px;\n"
        "border-color:black;\n")
        self.comboBoxYearLevel.setObjectName("comboBoxYearLevel")
        self.comboBoxYearLevel.addItem("")
        self.comboBoxYearLevel.addItem("")
        self.comboBoxYearLevel.addItem("")
        self.comboBoxYearLevel.addItem("")

        self.lineEditCourse2W = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditCourse2W.setGeometry(QtCore.QRect(120, 150, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEditCourse2W.setFont(font)
        self.lineEditCourse2W.setStyleSheet("background-color: rgb(229, 255, 252);")
        self.lineEditCourse2W.setObjectName("lineEditCourse2W")
        self.comboBox2W = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox2W.setGeometry(QtCore.QRect(120, 230, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox2W.setFont(font)
        self.comboBox2W.setObjectName("comboBox2W")
        self.comboBox2W.addItem("")
        self.comboBox2W.addItem("")
        EditWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EditWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 26))
        self.menubar.setObjectName("menubar")
        EditWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EditWindow)
        self.statusbar.setObjectName("statusbar")
        EditWindow.setStatusBar(self.statusbar)

        self.retranslateUi(EditWindow)
        QtCore.QMetaObject.connectSlotsByName(EditWindow)

#Function for retanslateUI, it set the text for the button, input widgets and etc
    def retranslateUi(self, EditWindow):
        _translate = QtCore.QCoreApplication.translate
        EditWindow.setWindowTitle(_translate("EditWindow", "Edit Window"))
        self.labelID_Number2W.setText(_translate("EditWindow", "Updated ID Number:"))
        self.labelID_Number3W.setText(_translate("EditWindow", "ID Number to be edited:"))

        self.labelName2W.setText(_translate("EditWindow", "Name:"))
        self.labelCourse2w.setText(_translate("EditWindow", "Course:"))
        self.labelYearlevel2W.setText(_translate("EditWindow", "Year Level:"))
        self.labelGender2W.setText(_translate("EditWindow", "Gender:"))
        self.pushButtonUpdate.setText(_translate("EditWindow", "Update"))

        self.comboBoxYearLevel.setItemText(0, _translate("AddWindow", "1st Year"))
        self.comboBoxYearLevel.setItemText(1, _translate("AddWindow", "2nd Year"))
        self.comboBoxYearLevel.setItemText(2, _translate("AddWindow", "3rd Year"))
        self.comboBoxYearLevel.setItemText(3, _translate("AddWindow", "4th Year"))
        
        self.comboBox2W.setItemText(0, _translate("EditWindow", "Male"))
        self.comboBox2W.setItemText(1, _translate("EditWindow", "Female"))
 
#Function that edit a student
    def edit_student(self):

        fileName = 'C:/Users/monti/A-CRUD/students.csv'
        id_number = self.lineEditIDNumber3W.text()
        ID_Number = self.lineEditIDNumber2W.text()
        Name = self.lineEditName2W.text()
        Course = self.lineEditCourse2W.text()
        Year_Level =self.comboBoxYearLevel.currentText()
        Gender = self.comboBox2W.currentText()

        index_student = None
        updated_data = []
        with open(fileName, "r", encoding="utf-8") as fileInput:
            reader = csv.reader(fileInput)
            counter = 0
            for row in reader:
                if len(row) > 0:
                    if id_number == row[0]:
                        index_student = counter   
                        student_data = []
                        student_data.append(ID_Number)
                        student_data.append(Name)
                        student_data.append(Course)
                        student_data.append(Year_Level)
                        student_data.append(Gender)
                        updated_data.append(student_data)
                    else:
                        updated_data.append(row)
                    counter += 1
                    



        # Check if the record is found 
        if index_student is not None:
            fileName = 'C:/Users/monti/A-CRUD/students.csv'
            with open(fileName, "w", encoding="utf-8",newline="") as fileInput:
                writer = csv.writer(fileInput)
                writer.writerows(updated_data)
                msg=QMessageBox()
                msg.setWindowTitle("--- Edit a Student ---")
                msg.setText("Succesfully updated student "+id_number+"")
                msg.setInformativeText("Updated to student with an ID Number: "+ID_Number+"")
                msg.setIcon(QMessageBox.Information)
                msg.setStandardButtons(QMessageBox.Ok|QMessageBox.Cancel)
                font=QtGui.QFont()
                font.setPointSize(12)
                font.setBold(True)
                font.setWeight(75)
                msg.setFont(font)
                msg.exec()
                
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditWindow = QtWidgets.QMainWindow()
    ui = Ui_EditWindow()
    ui.setupUi(EditWindow)
    EditWindow.show()
    sys.exit(app.exec_())
